services:
  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    expose:
      - 3306
    networks:
      - inception
    tty: true
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/wordpress
    expose:
      - 9000
    networks:
      - inception
    env_file: .env

  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sumseo/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sumseo/data/wordpress_data
      o: bind
