services:
  mariadb:
    image: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    expose:
      - 3306
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    image: wordpress
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - 9000
    depends_on:
      - mariadb
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
  

  nginx:
    image: nginx
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8443:443"
    depends_on:
      - wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    
networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sumseo/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sumseo/data/wordpress_data
      o: bind
